h1 {
    text-align: center;
    color: rgb(143, 70, 31);
    font-size: 4em;
}
.behind {
    background-color: bisque;
    width: 80%;
    margin-left: auto;
    margin-right: auto;
}
.subtitle {
    text-align: center;
}
body {
    background-image: url(https://cdn.pixabay.com/photo/2017/02/24/02/37/classroom-2093744_1280.jpg);
